title: Ryan Le  # your name (or website title) here
logo: "/images/photo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm an aspiring data analyst eager to enter the field. I have recently acquired skills in data analysis, including Python, R, SQL, Excel, Power BI, and Tableau. With a passion for uncovering insights, I'm ready to contribute to data-driven decision-making.
  <a href="https://www.linkedin.com/in/ryanleisme/" target="_blank">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
