title: Ryan Le  # your name (or website title) here
logo: "/images/photo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst experienced in Python, R, SQL, Excel, Power BI, and Tableau. With a strong ability to manipulate data, perform statistical analysis, and create impactful visualizations, I effectively communicate insights to drive informed decision-making.
  <br><br>
  <a href="https://www.linkedin.com/in/ryanleisme/" target="_blank">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
